version: '3.5'
services:
  site:
    image: webdevops/php-apache:7.4
    volumes:
      - .:/var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - dba:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=phpbr_event
      - MYSQL_ROOT_PASSWORD=root
volumes:
  dba:
